### PR TITLE
Upgrade to nan-2.1.0.

### PR DESCRIPTION
**Pull request by rossabaker**
This is completely untested.  My C++ is rusty and I don't know my way around Node.  But it compiles!

### CODE REVIEW

**Comment by mkrufky** [comment]
Please lets do a minor version bump to 0.2.13 after merging this

**Comment by mkrufky** [comment]
This looks OK to my eyes, but I haven't actually tested it either.  I'm much happier with the newer version of nan - less macro-looking code with less hidden functionality and much cleaner looking.  Please lets do a minor version bump to 0.2.13 after merging this

**Comment by rossabaker** [comment]
upgrade-utils did the heavy lifting here.  Everything else was related to `.ToLocalChecked`, where I either changed the order of operations or removed until it typechecked. 

I got to the point that I can send a DBUS message and see the right debug events in Google Music Electron.  They don't work, but I believe this to be an unrelated init problem in the browser.  I am still in over my head, but I have higher confidence in this PR now.

**Comment by Shouqun** [comment]
Thanks @rossabaker , pull request merged!

**Pull request merged**
